apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
        - name: grafanac
          image: satyams1999/grafana:latest
          ports:
          - containerPort: 3000
            name: grafana
          volumeMounts:
          - name: grafana-pvc
            mountPath: /var/lib/grafana
          imagePullPolicy: "Always"
      volumes:
      - name: grafana-pvc
        persistentVolumeClaim:
          claimName: volumeclaim-grafana
      nodeSelector:
        kubernetes.io/hostname: minikube
---
apiVersion: v1
kind: Service
metadata:
  name: grafana-service
  labels:
    app: grafana
spec:
  ports:
    - port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana  
  type: NodePort
---  