apiVersion: v1
kind: PersistentVolume
metadata:
  name: volume-prometheus
spec:
  capacity:
    storage: 25Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /prometheus
    server: 192.168.x.y
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volumeclaim-prometheus
  labels:
    app: prometheus
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
---